#!/bin/bash -e

ME=$(whoami)

# arch
pacman --noconfirm --needed -Syyu;
pacman --noconfirm --needed -S git base-devel;
git clone https://aur.archlinux.org/package-query.git /tmp/package-query;
cd /tmp/package-query && makepkg -si;
git clone https://aur.archlinux.org/yaourt.git /tmp/yaourt;
cd /tmp/yaourt && makepkg -si;

yaourt --noconfirm -S $(cat ./packagelist | xargs);

# copy all files
cp -R rootfs/* /

# move home dir files
mv /home/_TEMP/* /home/$ME/
rm -rf /home/_TEMP

# fonts
sed -i '/FONT/d' /etc/vconsole.conf || echo "FONT=Lat2-Terminus16" >> tee -a /etc/vconsole.conf

# nodm
if [[ -f /home/chronic/.Xresources ]]
  sed -i "/NODM_USER/c\NODM_USER='$ME'" /etc/nodm.conf
  sed -i "/NODM_XSESSION/c\NODM_XSESSION='/home/$ME/.xinitrc'" /etc/nodm.conf
fi

# cleanup
pacman --noconfirm -Rsn $(pacman -Qqdt);

# rebuild image
mkinitcpio -p linux
