#!/bin/bash -e
export ME=$(whoami)
export _HOME=/home/$ME

# arch
mkdir -p $_HOME/tmp
sudo pacman --noconfirm --needed -Syyu;
sudo pacman --noconfirm --needed -S git base-devel;
git clone https://aur.archlinux.org/package-query.git $_HOME/tmp/package-query;
cd $_HOME/tmp/package-query && makepkg -si --noconfirm;
git clone https://aur.archlinux.org/yaourt.git $_HOME/tmp/yaourt;
cd $_HOME/tmp/yaourt && makepkg -si --noconfirm;

yaourt --noconfirm -S $(cat packagelist | xargs);

# oh my zsh
curl -sSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh

# node
curl -o- https://raw.githubusercontent.com/creationix/nvm/master/install.sh | bash
export NVM_DIR="$_HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
nvm i 7.4.0;

# docker group
sudo usermod -aG docker $ME

# copy all files
sudo cp -R rootfs/* /

# move home dir files
sudo mv /home/_TEMP/.* $_HOME/
sudo rm -rf /home/_TEMP
sudo chown -R $ME:$ME $_HOME/*

# fonts
sudo sed -i '/FONT/d' /etc/vconsole.conf;
sudo echo "FONT=Lat2-Terminus16" >> /etc/vconsole.conf;

# ns switch resolution
sudo sed -i "/hosts:/c\hosts: files mdns4_minimal [!UNAVAIL=return] dns" /etc/nsswitch.conf;

# nodm
sudo sed -i "/NODM_USER/c\NODM_USER='$ME'" /etc/nodm.conf;
sudo sed -i "/NODM_XSESSION/c\NODM_XSESSION='/home/$ME/.xinitrc'" /etc/nodm.conf;
sudo systemctl enable nodm;

# local scripts
sudo chmod +x /usr/local/bin/*;

# cleanup
sudo pacman --noconfirm -Rsn $(pacman -Qqdt);

# zerotier
sudo systemctl enable zerotier-one
sudo systemctl start zerotier-one
sudo cat /var/lib/zerotier-one/authtoken.secret >>$_HOME/.zeroTierOneAuthToken
chmod 0600 $_HOME/.zeroTierOneAuthToken

# rebuild image
sudo mkinitcpio -p linux;

# stick in aliases file to .zshrc
echo "source ~/.zsh_aliases" >> $_HOME/.zshrc;

sudo reboot now;
